### ISSUE TITLE
Allow reset of used tokens?

### ISSUE THREAD

**Issue by Jpja** [CounterpartyXCP/cips#53]
Should assets with previous token transfers be allowed to reset divisibility? 

The implementation on Dogeparty does allow this:

![image](https://user-images.githubusercontent.com/8447505/184293970-dfb6249a-d04c-48ee-9aba-b93be06d1b9f.png)

In theory any asset can be reset if all tokens are returned to the issuer. 

My concern is that divisibility thus changes from an immutable to a mutable property. Wallets must rely on API for every transaction. A dishonest API can cause loss of fund. A best practice for light wallets should be to have a local table of divisibility statuses.

The solution is to remove `AND quantity > 0` from the SQL command. Since the `balances` table keeps records of addresses that previously held the token, any used asset has `len(balances) > 1` and keeps their immutable status.

**Comment by jdogresorg** [comment]
Thank you for raising your concern JP.

What about cases where the asset owner registered the token and issued 1.00000000 tokens, then later swept asset balances and asset ownership to a new addresses (I have actually done this with a few thousand assets). With your proposed fix, the asset owner would be out of luck simply for moving the asset supply and as to a new address and would not be able to reset the token/supply because the balances table would show more than 1 record

**Comment by Jpja** [comment]
Oh, I though this would affect zero or very few asset. Now knowing there are a few 1000 cases, I think the best tradeoff is to use the dogeparty implementation after all.
