### ISSUE TITLE
CIP28 - Consensus code?

### ISSUE THREAD

**Issue by Jpja** [CounterpartyXCP/cips#74]
Will Counterparty nodes process BTNS instruction and keep track of token balances, etc? I.e. a consensus change.

Or is this a layer on top of Counterparty that's optional for nodes to process? I.e. Counterparty will only store the broadcast as-is, not a change to consensus code.

**Comment by Jpja** [comment]
I agree that we should encourage building new solutions on top of Counterparty, and that it is ideal to use the broadcast system for this.

An alternative token system is intellectually interesting, and it's great that you give a framework for people experimenting with this.

However, I am very much against officially _promoting_ an alternative name/token system. Counterparty's strength is having one such system. Even Ethereum, with its programmable smart contracts, has gravitated to ERC20, ERC721 and ENS, which is essentially what Counterparty's name/token system is. Imo CIPs should be made to add value to this one system. I recommend giving "Deferred" status to this CIP.

**Comment by jdogresorg** [comment]
Just because something is a CIP in the repo does not mean that it is a part of CP, or that it is a process that has to be used on CP. 

A perfect example of this is Blockchain Validated Asset Metadata (BVAM)... just a CIP that defines a process... been around for years, cool idea, but no one really uses it... I expect BTNS to see the same fate...

I do not think that "Deferred" is appropriate at this time, the spec was just created a few days ago, and already "Deferred"?!? Why is BVAM not "Deferred" then?

Thanks for raising this issue tho, because I do think that this "type" is more `Informational` than `Standards`, at least according to the CIP Type definitions. I have updated CIP28 to be `Informational`

https://github.com/CounterpartyXCP/cips/blob/master/cip-0001.md?plain=1#L20-L24

I get your point tho, your uncomfortable with BTNS living in the CIP repo, cuz you think it denotes that Counterparty supports this process... and others could have the same mis-perception. 👍 

For the record, I had no plan to publish BTNS as a CIP, and in fact planned to have the Stamps/SRC Devs publish BTNS and SRC-20.1 together from the their own repo.... In this way the SRC devs would be introducing the BTNS and SRC-20.1 to their community... letting them take the ball... letting them get all the glory for writing BTNS and SRC-20.1... so they could just move forward to a new better spec. I worked all week on these specs, towards the goal of SRC devs doing the release on their own, and trying to get the SRC devs to engage more.

Can verify below with git commits and screenshots:
https://github.com/jdogresorg/stampchain/commits/main

![image](https://github.com/CounterpartyXCP/cips/assets/376028/f0db1ff0-1ea5-4407-a319-910b1fcf1780)

However, over the course of the week, it became clear (to me at least), that the warnings about abuse were not being taken seriously by the src-20 devs, and progress to move off of SRC-20 was not moving fast enough. 

My choice was either :
  - Force an emergency `counterparty-lib` release to add fee on numerics to stop abuse (drastic and undesirable)
OR
  - Publish the BTNS as a CIP, notify the community that there was a new open name system they could experiment with

The goal behind releasing this CIP in this manner was :
1. Give degens who are focused on src-20 and spamming those abusive txs, something "new" to try while SRC-20.1 was written/refined by the SRC devs.

3. Put out a new "OPEN" spec to demonstrate to newcomers how we do things here on CP (open-source/decentralized, not closed-source/centralized)

4. Demonstrate to SRC Devs how the BTNS could work (what better way than having it actually working), and hope they use this method for experimenting, instead of clogging up the asset table with non-usable assets (no supply, locked).

5. Allow for experimentation to take place on Counterparty in a safe/sane/responsible manner (guiding ppl to broadcasts)

For the record, I think all this BRC-20/SRC-20 mania is a shorter-term phenomena, and it will play itself out pretty soon.

However, in the meantime, why not support experimentation on Counterparty vs shutting it down?

**Comment by jdogresorg** [comment]
FYI... I am building an open-source BTNS indexer and data tables to have all the BTNS data live outside/independent of the CP database

I am doing best I can to try and support BTNS system and experimentation, while still making it clear that this is NOT officially a part of the Counterparty protocol.

![image](https://github.com/CounterpartyXCP/cips/assets/376028/9438e2bb-1c69-4597-af92-31fb91067ed9)

**Comment by jdogresorg** [comment]
@Jpja FYI... I updated CIP28 to support versioning, indicate required fields, and to direct ppl to the `official` repo for BTNS.

The thought process here is the basic BTNS is defined as an Informational CIP, but I am able to develop additional BTNS `actions` and specs in a separate repo from the CIP repo.

My hope is that this further clarifies that the BTNS is not officially endorsed by CP... and I will add something to that effect to my BTNS repo README shortly.

https://github.com/CounterpartyXCP/cips/pull/78

**Comment by jotapea** [comment]
> However, I am very much against officially promoting an alternative name/token system. Counterparty's strength is having one such system.

Agree 100%.

**Comment by jotapea** [comment]
I believe CIP28 should be withdrawn for THE reason stated above.

**Comment by jdogresorg** [comment]
I have updated my BTNS repo to clarify that this is not an officially supported project by CP weeks ago...

https://github.com/jdogresorg/Broadcast-Token-Naming-System

Having "withdrawn" status is silly IMO because it is still a workable solution (it simply defines a framework for how a name system COULD work).  Having a CIP in a repo DOES NOT indicate that it is official supported, it is just a PROPOSAL. Should we have no proposals in the CIP which are not 100% supported by CP? What is the point of a proposal system then?

IMO... this is a waste of time going back and forth on this.

@Jpja Please close this issue... If you want me to remove CIP28 entirely, just let me know and i'll submit a PR to remove it entirely... tired of the drama related to BTNS.... My focus is on building on the BTNS and bringing more activity to CP... not on bickering over status of CIPs.

**Comment by jotapea** [comment]
@Jpja Please reopen, this has not been "completed". https://github.com/CounterpartyXCP/cips/discussions/97#discussioncomment-6270249

**Comment by hydren-crypto** [comment]
this is funny "the warnings about abuse were not being taken seriously by the src-20 devs, and progress to move off of SRC-20 was not moving fast enough." 

For posterity - the warnings were taken seriously and action was taken as soon as possible from all available stamps/src-20 devs. It took more than a week to develop a new protocol from part time devs working as a hobby. In which SRC-20 was pushed completely outside of CP due to the unnecessary threats of XCP fees on stamps and a potential fork situation. All threats were due to potential performance issues because of design problems of a mere 8GB CP database that was in theory growing too fast due to the rapid adoption of SRC-20. These are database problems which should be remediated in future versions of CP.

The division, threats, and lack of dev support to collaborate on a proper token solution on top of CP alienated the stamp/src-20 community and forced the team to create solutions outside of CP for SRC-20.  BTNS appears to have been simply created in isolation without any input or feedback from the stamps devs as a competitor to SRC-20 which ideally would have been built collaboratively with the stamp/src-20 community to experiment together. All with the goal of growing the CP ecosystem. In which more devs would have been willing to contribute to CP dev and the database problems. Furthermore it appears that BTNS development takes away from work that could be done to further build upon CP overall. 

The broadcast solution was not ideal for the initial requirements of SRC-20 and it's future vision, however it is agreed that this is the best method within CP in it's current design. 

ofc now we are seeing more adoption of such seemingly hilarious tokens given the release of runes. meanwhile the stamps/cp community is split while more users are surely drawn to runes. Maybe not a problem given the user base, but it does impact community growth and long term support/ new interest in CP.

can i speak to the manager? lol
