### ISSUE TITLE
Fee on Numeric Assets

### ISSUE THREAD

**Issue by Jpja** [CounterpartyXCP/cips#77]
I advice against doing the emergency fork today (mentioned in the Telegram dev chat).

Although I am in favor of fees on numeric assets, a fork without a public announcement and debate is a breach of the "social contract" imo.

Also, I believe a fee will have little effect in the immediate term. The alleged spammers already pay several dollars in BTC fees per asset, so 0.25 XCP (~$1) won't change much. However, I do believe an XCP fee will deter "spam" in the medium term as the market will run dry if they continue.

I wrote a CIP this morning (https://forums.counterparty.io/t/fee-on-numeric-assets/6601/3). Feel free to modify it as you see fit, announce it in the main channels, and _if_ there's a general support for it we should fork asap.

**Comment by jotapea** [comment]
Agree in adding a fee to numeric assets. If XCP is burned BTC, then ASSET should be burned XCP*.

(* Note: is not exactly the same, as the quantity of XCP issued was also tied to the amount of burned BTC (per block distribution), whereas for ASSET the XCP fee is static irrespective of quantity issued by the asset... MAYBE this is something to reconsider, but that is a separate topic.)

In my view the ideal Counterparty protocol would burn XCP only when issuing assets, as the whole system exists in service to the financial+ actions done on assets.

Currently this is not the case, as it is also used to balance the "impact" (which needs to be specific: in long term disk space, one query time, query repetition, etc...) of actions done to the DB. This might be a good design choice, but my problem with it is that it seems arbitrary because other actions that have impact on the DB don't have any fee. Also, the DB design itself can be improved so actions have less impact on the DB.

Having said all this, I would not mind leaving the non-name registering XCP fees for now.

Then, about the new fee structure for numerics, I think it can look something like this:

If the fee for \<NAME> asset registration is N XCP, \<ANUMBER> asset registration is N/10 (sub-assets inclusive). I believe having the same fee for numeric-only vs numeric-sub-assets will incentivize the use of sub-assets, increasing rich / creative relations between assets.

**Comment by jotapea** [comment]
@Jpja Why all the closed issues? I think that at least this one should be kept open. (And https://github.com/CounterpartyXCP/cips/issues/82 is highly related to next steps in solving scaling issues.)

**Comment by jotapea** [comment]
For posterity, while I still think that the top use case for XCP is to protect the namespace, I have always liked A LOT that numeric assets don't require XCP.

So after more time to process all that happened with STAMPs, now I lean more into NOT adding a fee to numerics. And I would extend this to also having NO fee for sub-assets, as I feel this will help in promoting their use.
