### ISSUE TITLE
CIP29 - Feasible to no longer save invalid issuances?

### ISSUE THREAD

**Issue by Jpja** [CounterpartyXCP/cips#80]
CIP29 proposes: "no longer save invalid transactions to the issuances table."

Without this update, issuance that don't pay the XCP fee would simply be added the `issuances` table as invalid. Thus a spammer, if continuing as before, would keep adding rows to the table without paying any XCP fees.

I have not tested for deeper implications by not adding invalid transactions. This must be investigated.

_P.S. If we decide on keep saving invalid transaction to the `issuances` table, we at least prevent invalid issuances from being saved to the `assets` table as well. This in itself should justify adding the fee._

**Comment by jdogresorg** [comment]
You bring up a good point, however stuffing issuances into the issuances table at this time is not an issue that needs addressed. Perhaps at some future time when we have a case where someone is spamming invalid issuances with HUGE descriptions, then we can tackle this issue.

IMO we need to keep invalid issuances in the issuances table in order to determine and relay the status of the transaction to the user (CP determines state at time of execution of action, and saves state... valid, invalid, etc) Without saving invalid issuances, we would have no way to know the state of the issuance, nor why it failed, and looking that information up retroactively would be difficult (to determine state of balances at time of issuance execution). 

The benefits of being able to easily see "Oh, my issuance failed because I ran out of XCP, let me send my address some more XCP" is more helpful than hiding this failure entirely from the user. 

I oppose this change at this time, as I feel it requires more discussion before being implemented in a CIP.

**Comment by Jpja** [comment]
Ok, fees will at least prevent invalid issuances from filling up the assets table and `status=invalid` should discourage using the issuances table as data storage (or at least make a clean way for explorers to filter out invalid issuances).

Agree that storing invalid tx's or not needs discussion and a separate CIP.  

I will remove the line "no longer save invalid transactions to the issuances table" from CIP29.

**Comment by moonblink** [comment]
irt CIP-20 XCP Fees https://github.com/CounterpartyXCP/cips/blob/master/cip-0029.md

is it possible to have BTC fees instead, that way users aren't required to make multiple transactions in order to acquire xcp and then burn? The xcp burn could perhaps be automated on the backend in aggregate reducing transaction costs?

**Comment by jotapea** [comment]
This should not be considered, as it goes against the core architecture of the protocol.

https://www.xcp.dev/messages

Notice that each message has a `category` and a `command`. The category is the table, the command is either 'insert' or 'update'. The protocol is ALL about keeping the STATE of consensus based on these messages being followed. Inserting DATABASE rows or updating them.

It works and I would not mess with this.
