### ISSUE TITLE
CIP29 - Correct assumption on node impact?

### ISSUE THREAD

**Issue by Jpja** [CounterpartyXCP/cips#82]
The motivation for CIP29 is: _"Balance the cost of issuing assets with that of running nodes/infrastructure, and to encourage use of broadcasts when issuances are not strictly needed."_

@jotapea, who runs xcp.dev, disagrees
![image](https://github.com/CounterpartyXCP/cips/assets/8447505/d6c7c227-53f1-4bec-90c6-d15ce81974a8)

Can we quantify the impact of issuing 10,000 assets? 100k? 1M?
What is the big O notation?

**Comment by jotapea** [comment]
Haha!

Yeah the way the protocol works is by inserting all CNTRPRTY messages found in Bitcoin, even if they are invalid. So after adding a fee, if people continue issuing assets without XCP, all these would still be inserted into the protocol's SQLite DB as invalid issuances.

The disk space requirements are not diminished or protected by the fee. Actually the disk requirements are affected much more by the highly denormalized database design than the genesis of new assets.

I am actually in agreement with adding a fee to numerics, but is the currently stated motivation of "balance of cost" that I found insincere.

If we are going to analyze performance (CPU and RAM), I would first look at the impact of adding `reset` and treating these like any other asset.

**Comment by Jpja** [comment]
I've simulated DB growth and the conclusion is clear. Both `assets` and `issuances` tables scale worse than O(n).

A simple asset lookup will take more than 100ms with 1M assets. 
![image](https://github.com/CounterpartyXCP/cips/assets/8447505/5382b8b8-0153-4e03-be73-9b30b3733952)

I conclude that the assumption on node impact is correct and something must be done to reduce the growth in assets and issuances.

Python scripts used for testing:
https://forums.counterparty.io/t/testing-scalability-of-assets-and-issuances-tables/6621

**Comment by jotapea** [comment]
@Jpja great that you took the time to do that! (But why not post it here in GitHub? Seems appropriate...)

About your test query:

```sql
SELECT COUNT(*) FROM issuances WHERE asset = 'X'
```

The performance of this would not change after the introduction of a fee because invalid issuances are also counted. Also, another feature that arguably affects even more issuance inserts is `sweeps`.

But your analysis with comparing to the `assets` table hit the nail in the head. Before 'reset', the `assets` table was always the most direct way to access an asset's divisibility, because this table stores the block of the genesis issuance (this is how it is done in [xcp.dev](https://github.com/CNTRPRTY/xcpdev/blob/01baf52067bc24f22aba437b327b3c9ba1d5e423/server/express_server/src/queries.js#L236)).

After the reset, if the protocol wants to treat reset assets like any other, the `issuances` table is the only one that can be queried. This is because it is not relying in the genesis issuance block any more, but in the last (valid) issuance instead which is not stored anywhere else. Thus you can not longer rely on the `assets` table, and need to query the `issuances` table by name and status (and not block) EVERY time that divisibility is required.

**Comment by loon3** [comment]
is there any reason divisibility couldn't be stored/updated in the assets table?

**Comment by jotapea** [comment]
Technically, no. Anything can be done (just like reset was done).

But it would take the database deeper into denormalization. If the protocol needs to scale, this is not the path to go. Denormalization needs to be delegated to the application layers.

And on a more philosophical level, the current `assets` table could literally be renamed to `assets_genesis`. I would not do updates to a genesis table, only inserts.
