### ISSUE TITLE
CIP29 - Issuances triggered by sweep need fee

### ISSUE THREAD

**Issue by Jpja** [CounterpartyXCP/cips#83]
Sweep is a special message type. It triggers an issuances for each asset ownership held by an address. The 0.01 XCP fee/asset should be applied.

I think it's cleaner with an all-or-nothing approach:
- check if XCP balance is sufficient to sweep all assets
- If sufficient XCP: 
  - deduct fee for entire sweep
  - go ahead with sweep
 If insufficient XCP:
  - cancel sweep

The fixed 0.50 XCP fee is no longer needed. I will revise CIP29 to make this clear.

**Comment by jotapea** [comment]
(Maybe I should make a new issue, but since there are already 3 based on CIP29 I don't want to dilute the conversation even more...)

I believe that the addition of a fee for non-genesis issuances is a BAD move, the fee should only be needed for the asset name registration.

The logic of database impact is flawed in my opinion. There is no difference in fee for people issuing a 1 quantity asset vs a 1000000000 one. Clearly one will impact the DB much more than the other, then why not make the second pay more fees?

If XCP is burned BTC, then \<ASSET> should be burned XCP. And that's it, I would not charge XCP for anything else in the protocol.

Sweeps are a convenience, but they're kind of messed up if they have no limits based on the current database design. So I can accept keeping the sweep XCP fee or even make it adjusted based on the size of the sweep...

BUT I would not make these an "extension" of just charging for every issuance update.

**Comment by Jpja** [comment]
The underlying problem is growth of the `issuances` table. According to my simulation (https://forums.counterparty.io/t/testing-scalability-of-assets-and-issuances-tables/6621/3) this table scales worse than O(n). 

A sweep from an address with N assets will write N new rows to the `issuances` table. If nothing else, we should add a proportional fee to sweeps. Currently it is fixed 0.5 XCP, so on the margin it is 0.5 for the first asset and 0 for the rest. The cost per asset is thus 0.0005 is for an address with 1000 assets. A fee of 0.01 XCP per asset will discourage such use.

P.S. I do not have the current testnet DB. Can you confirm that this testnet tx (7fb8a88eed784aa5e5547ea787017fffefee437a672b075b12e91ca14b18a41f) is stored in the `sweeps` table as invalid, and that no rows were added to `issuances` ?

**Comment by jotapea** [comment]
I don't have a testnet node running at the moment, but I would be surprised if the sweep creates invalid issuance messages (thus DB inserts).

And I agree a choice has to be made regarding this, is either remove the feature or add a fee proportional to the moving of assets. But then I see usability problems where the sweep can drain people's XCP balance... so the UX will require warning about this.

With a redesign of the database, maybe the XCP fee could be removed completely though.

**Comment by jotapea** [comment]
And I just realized that another option is to adjust the sweep to only work for balances and not for issuance transfers. And to make up for the new limitation, remove the XCP fee.

**Comment by Jpja** [comment]
I think the fee for sweeping balances should be in line with that of multi-sends and dividends. Exact same DB impact, right?

**Comment by jotapea** [comment]
I just see things a bit different, DB impact is so relative. Something like destroys can have a lot of DB impact and those don't pay any fee.

As I have mentioned I would make XCP be only about asset names, and cheaper for numerics (same as subassets).

**Comment by Jpja** [comment]
All actions pay BTC fee. That's usually enough. Certain special cases need XCP fee on top.

1. Dividend, sweep and multi-send can add very large amount of data to the DB from just one BTC tx. Therefore XCP fee is needed. 

2. The name space needs protection.

**Comment by jotapea** [comment]
Yes I get that. But part of my point is that the DB impact is also based on the DB design.

By the adding data logic, then the XCP fee needs to be relative to the size always. Is it relative in any of the cases in 1. ? Or is it static always like sweeps currently are?

**Comment by Jpja** [comment]
Dividend and multi-send have proportional fees. Sweep has a fixed fee.
